#### Unit 6 | Assignment-WeatherPy
######            What's the weather like as we approach the equator?


In this example, you'll be creating a Python script to visualize the weather of 500+ cities across the world of varying distance from the equator. To accomplish this, you'll be utilizing a [simple Python library](https://pypi.python.org/pypi/citipy), the [OpenWeatherMap API](https://openweathermap.org/api), and a little common sense to create a representative model of weather across world cities.

Your objective is to build a series of scatter plots to showcase the following relationships:
* Temperature(F) vs. Latitude * Humidity(%) vs. Latitud  * Cloudiness(%) vs. Latitude * Wind Speed(mph) vs. Latitude

Your final notebook must:
* Randomly select **at least** 500 unique (non-repeat) cities based on latitude and longitude.
* Perform a weather check on each of the cities using a series of successive API calls.
* Include a print log of each city as it's being processed with the city number, city name, and requested URL.
* Save both a CSV of all data retrieved and png images for each scatter plot.

As final considerations:

* You must use Matplotlib to create your plots.
* You must include a written description of three observable trends based on the data.
* You must use proper labeling of your plots, including aspects like: Plot Titles (with date of analysis) and Axes Labels.
* You must include an exported markdown version of your Notebook called  `README.md` in your GitHub repository.
* See [Example Solution](WeatherPy_Example.pdf) for a reference on expected format.

#### Hints and Considerations

* You may want to start this assignment by refreshing yourself on the [geographic coordinate system](http://desktop.arcgis.com/en/arcmap/10.3/guide-books/map-projections/about-geographic-coordinate-systems.htm).

* Next, spend the requisite time necessary to study the OpenWeatherMap API. Based on your initial study, you should be able to answer  basic questions about the API: Where do you request the API key? Which Weather API in particular will you need? What URL endpoints does it expect? What JSON structure does it respond with? Before you write a line of code, you should be aiming to have a crystal clear understanding of your intended outcome.

* Though we've never worked with the [citipy Python library](https://pypi.python.org/pypi/citipy), push yourself to decipher how it works, and why it might be relevant. Before you try to incorporate the library into your analysis, start by creating simple test cases outside your main script to confirm that you are using it correctly. Too often, when introduced to a new library, students get bogged down by the most minor of errors -- spending hours investigating their entire code -- when, in fact, a simple and focused test would have shown their basic utilization of the library was wrong from the start. Don't let this be you!

* Part of our expectation in this challenge is that you will use critical thinking skills to understand how and why we're recommending the tools we are. What is Citipy for? Why would you use it in conjunction with the OpenWeatherMap API? How would you do so?

* In building your script, pay attention to the cities you are using in your query pool. Are you getting coverage of the full gamut of latitudes and longitudes? Or are you simply choosing 500 cities concentrated in one region of the world? Even if you were a geographic genius, simply rattling 500 cities based on your human selection would create a biased dataset. Be thinking of how you should counter this. (Hint: Consider the full range of latitudes).

* Lastly, remember -- this is a challenging activity. Push yourself! If you complete this task, then you can safely say that you've gained a strong mastery of the core foundations of data analytics and it will only go better from here. Good luck!

# Walsh Weather
### Observations:
1.

2.

3.

In [160]:
#Import dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import json
import random
import time
import openweathermapy.core as owm
from citipy import citipy

In [119]:
#Creating cities by setting rectangle groupings

#api_key = "d4c7fc687a3ecaf9670515da999f1a2b"
#base_url= "http://api.openweathermap.org/data/2.5/box/city?bbox=-180,-90,180,90"
#units ="imperial"


#query_url = base_url + "&appid=" + api_key + "&units="+ units
#response = requests.get(query_url).json()
#response
#response_df = pd.DataFrame(response)

In [133]:
#Selecting cities from complete list of cities available from openweathermaps  http://bulk.openweathermap.org/sample/
raw_data =pd.read_json("city_list.json")
raw_city_list= raw_data[["name",'id',"country", "coord"]]
raw_city_list.head()
#new = raw_city_list["coord"]

               name       id country                                 coord
0            Hurzuf   707860      UA  {'lon': 34.283333, 'lat': 44.549999}
1           Novinki   519188      RU  {'lon': 37.666668, 'lat': 55.683334}
2            Gorkhā  1283378      NP         {'lon': 84.633331, 'lat': 28}
3  State of Haryāna  1270260      IN                {'lon': 76, 'lat': 29}
4         Holubynka   708546      UA  {'lon': 33.900002, 'lat': 44.599998}

In [136]:
# Get and store target url for each city in list by city name
base_url= "http://api.openweathermap.org/data/2.5/weather"
api_key = "d4c7fc687a3ecaf9670515da999f1a2b"
units ="imperial"

#Testing
#target_url = base_url + "?appid=" + api_key + "&units="+ units +"&id=" + "708546"
#response = requests.get(target_url).json()
#response

In [137]:
#weather_df = pd.DataFrame(columns = ["Name","Max Temp", "Humidity","Cloudiness","Wind Speed"])
#weather_df

In [163]:
#create loop to hold target url with counter

count= 0
group = 1

weather_df = pd.DataFrame(columns = ["Name","Latitude","Longitude","Max Temp", "Humidity","Cloudiness","Wind Speed", "Date"])


for x in range(2):
    sample_list = raw_city_list["id"].sample(60).tolist()
    
    for x in sample_list:
        print(f"Processing Record {count} of Set {group}")
        target_url = base_url + "?appid=" + api_key + "&units="+ units +"&id=" + str(x)
        response = requests.get(target_url).json()
        name= response["name"]
        temp = response["main"]["temp_max"]
        clouds = response["clouds"]["all"]
        humidity = response["main"]["humidity"]
        wind = response["wind"]["speed"]
        lat = response["coord"]["lat"]
        lon = response["coord"]["lon"]
        date = response["dt"]
        weather_df =weather_df.append({"Name":name,"Latitude":lat,"Longitude":lon,"Max Temp":temp, "Humidity":humidity,"Cloudiness":clouds,"Wind Speed":wind,"Date":date}, ignore_index=True)
        print(target_url)
        count +=1
        
    group +=1
    #time.sleep(62)

Processing Record 0 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3021532
Processing Record 1 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=4307879
Processing Record 2 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2058005
Processing Record 3 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2518736
Processing Record 4 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=712755
Processing Record 5 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1800603
Processing Record 6 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3114225
Processing Record 7 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2890321
Processing Record 8 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3066637
Processing Record 9 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1690317
Processing Record 10 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3181969
Processing Record 11 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3156980
Processing Record 12 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2984192
Processing Record 13 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=6358444
Processing Record 14 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3532858
Processing Record 15 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=6358046
Processing Record 16 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3146831
Processing Record 17 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=897456
Processing Record 18 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=518103
Processing Record 19 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1605179
Processing Record 20 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2661383
Processing Record 21 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=6536332
Processing Record 22 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2743963
Processing Record 23 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1015633
Processing Record 24 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1855203
Processing Record 25 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2725201
Processing Record 26 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=6357409
Processing Record 27 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2207258
Processing Record 28 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=7638154
Processing Record 29 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=618067
Processing Record 30 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=738372
Processing Record 31 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2037820
Processing Record 32 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=8058066
Processing Record 33 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=5915070
Processing Record 34 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3092643
Processing Record 35 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=4317985
Processing Record 36 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=8058265
Processing Record 37 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1788077
Processing Record 38 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3430834
Processing Record 39 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3437982
Processing Record 40 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=6111731
Processing Record 41 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=6439270
Processing Record 42 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3062417
Processing Record 43 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3107006
Processing Record 44 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=7407361
Processing Record 45 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=5249503
Processing Record 46 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=6609446
Processing Record 47 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=4120524
Processing Record 48 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1863917
Processing Record 49 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2971054
Processing Record 50 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2164975
Processing Record 51 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=5162390
Processing Record 52 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=662437
Processing Record 53 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=755438
Processing Record 54 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=562814
Processing Record 55 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2810832
Processing Record 56 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=4632591
Processing Record 57 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1870434
Processing Record 58 of Set 1

http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3607381
Processing Record 59 of Set 1
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=5445479
Processing Record 60 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=876123
Processing Record 61 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=6442111
Processing Record 62 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2776791
Processing Record 63 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=7531072
Processing Record 64 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=4265507
Processing Record 65 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3522293
Processing Record 66 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3169980
Processing Record 67 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2959980
Processing Record 68 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=4017199
Processing Record 69 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=7257804
Processing Record 70 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1279394
Processing Record 71 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=8013136
Processing Record 72 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1996550
Processing Record 73 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2962658
Processing Record 74 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2841629
Processing Record 75 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=5263045
Processing Record 76 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1153081
Processing Record 77 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2690843
Processing Record 78 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1910091
Processing Record 79 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=6137947
Processing Record 80 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1200682
Processing Record 81 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1807082
Processing Record 82 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=8012861
Processing Record 83 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3009732
Processing Record 84 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3527164
Processing Record 85 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1264198
Processing Record 86 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=4099974
Processing Record 87 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=788819
Processing Record 88 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=4167127
Processing Record 89 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2917700
Processing Record 90 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=684802
Processing Record 91 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1812288
Processing Record 92 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=6361437
Processing Record 93 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3126945
Processing Record 94 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=4762988
Processing Record 95 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=4646772
Processing Record 96 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3081562
Processing Record 97 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2949808
Processing Record 98 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3449795
Processing Record 99 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2961409
Processing Record 100 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3323924
Processing Record 101 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=6454601
Processing Record 102 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3453297
Processing Record 103 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2920006
Processing Record 104 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=227592
Processing Record 105 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2955112
Processing Record 106 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2084734
Processing Record 107 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=301251
Processing Record 108 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2965111
Processing Record 109 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1634131
Processing Record 110 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=7293134
Processing Record 111 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=1645376
Processing Record 112 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3209102
Processing Record 113 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3165807
Processing Record 114 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2475680
Processing Record 115 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=7287054
Processing Record 116 of Set 2

http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=125188
Processing Record 117 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2980411
Processing Record 118 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=2918752
Processing Record 119 of Set 2
http://api.openweathermap.org/data/2.5/weather?appid=d4c7fc687a3ecaf9670515da999f1a2b&units=imperial&id=3689147

In [164]:
weather_df

,Name,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Date
0,Dessenheim,47.98,7.49,37.40,100,90,3.36,1510626600
1,Sebree,37.61,-87.53,42.80,86,1,3.36,1510626900
2,Wongan Hills,-30.88,116.70,80.71,35,0,16.08,1510628860
3,El Altet,38.27,-0.54,48.20,36,0,10.29,1510628400
4,Batal’ne,45.20,35.62,56.55,91,48,12.84,1510628862
5,Miaogou,36.88,107.92,34.18,38,36,4.38,1510628862
6,Pasantes,42.75,-7.22,29.32,89,0,2.37,1510628863
7,Kirkel,49.28,7.23,32.00,98,12,2.24,1510628340
8,Roztoky,50.03,13.87,35.60,94,75,8.05,1510626600
9,San Antonio,15.15,120.69,87.80,62,40,9.17,1510628400
10,Bobbio Pellice,44.81,7.12,35.60,51,0,2.24,1510626000
11,Floro,61.60,5.03,35.60,93,90,20.80,1510627800
12,Redon,47.65,-2.08,35.60,100,0,2.24,1510626600
13,Yebra de Basa,42.49,-0.24,35.60,51,0,8.05,1510628400
14,Anenecuilco,18.77,-98.98,61.77,47,0,4.90,1510628868
15,Torremocha del Campo,40.93,-2.58,30.45,86,0,12.88,1510628868
16,Lundamo,63.13,10.30,28.40,100,0,5.82,1510627800
17,Sinazongwe,-17.26,27.46,71.22,100,68,3.00,1510628870
18,Novosëlki,57.77,43.67,31.03,91,92,8.81,1510628870
19,Waeng Noi,15.80,102.42,85.89,64,0,8.25,1510628871
20,Broc,46.61,7.10,35.60,100,90,1.12,1510626000
21,Borgonovo Val Tidone,45.01,9.44,39.20,93,20,1.12,1510626000
22,Zelhem,52.01,6.35,33.80,100,90,1.12,1510628100
23,Brink’s Vlakfontein,-26.18,27.80,77.00,68,8,11.41,1510624800
24,Nishinoomote,30.73,131.00,66.20,93,75,5.82,1510626780
25,Arsta,59.30,18.05,28.40,100,0,4.70,1510627800
26,Cañete,40.05,-1.64,30.90,56,0,14.63,1510628875
27,East Brisbane,-27.48,153.04,77.00,41,20,9.17,1510626600
28,Sanli,30.78,118.25,58.66,93,92,4.56,1510628876
29,Chitcani,46.78,29.62,46.40,93,40,5.82,1510626600
...,...,...,...,...,...,...,...,...
90,Barlad,46.23,27.67,48.20,100,75,12.75,1510626600
91,Dongsha,30.31,122.14,63.97,100,64,12.17,1510628914
92,Alcaine,40.95,-0.71,48.20,31,0,5.82,1510628400
93,Calzada de Tera,41.99,-6.08,23.65,73,0,2.55,1510628915
94,Hanover County,37.75,-77.48,42.80,87,1,3.36,1510628100
95,Obion,36.26,-89.19,44.60,86,1,8.08,1510628160
96,Wola Kożuszkowa,52.51,18.22,32.00,91,90,5.82,1510628400
97,Besenthal,53.53,10.73,32.00,94,20,3.36,1510627800
98,Santa Rosa de Lima,-10.65,-37.19,77.00,88,40,9.17,1510624800
99,Sneem,51.83,-9.90,53.80,97,92,10.83,1510628919
100,Rohrberg,47.23,11.92,32.00,91,75,1.12,1510626000
101,Rioz,47.42,6.07,35.60,100,75,3.36,1510628400
102,Pocrane,-19.62,-41.64,65.86,92,92,3.22,1510628920
103,Glehn,50.60,6.60,37.40,100,40,1.12,1510628160
104,Ntungamo,-0.88,29.65,64.02,100,48,2.37,1510628921
105,Ashausen,53.36,10.14,32.00,91,0,4.70,1510627800
106,Umbimi,-6.15,143.65,64.69,85,56,2.89,1510628922
107,Selendi,38.74,28.87,38.68,88,92,2.26,1510628923
108,Corofin,52.95,-9.06,51.80,100,75,10.29,1510628400
109,Nganjuk,-7.61,111.90,84.72,69,48,4.00,1510628924
110,North Lodge,54.87,-1.56,50.00,87,75,21.92,1510627800
111,Doko,-8.08,112.37,84.72,69,48,4.00,1510628925
112,Schmakentin,53.88,11.57,32.00,100,20,2.24,1510626000
113,Teora,40.85,15.25,42.80,81,75,2.37,1510624500
114,Tleta,36.79,5.89,53.60,76,75,25.28,1510624800
115,Sarmenstorf,47.31,8.25,39.20,93,90,4.70,1510628400
116,Malard,35.67,50.98,48.20,42,0,6.93,1510626600
117,Sainte-Marie-Plage,42.73,3.04,48.20,91,0,31.09,1510628400
118,Gotha,50.95,10.70,33.80,83,20,8.05,1510627800
119,Barranquilla,10.96,-74.80,82.40,94,40,3.36,1510624800

In [ ]:
# Collect x and y coordinates
#Lat vs temp
x_axis_lat =
y_axis_temp =
# Lat vs Humidity
x_axis_lat =
y_axis_humidity=
#Lat vs Cloudiness
x_axis_lat =
y_axis_humidity =
#Lat vs Wind Speed
x_axis_lat =
y_axis_humidity =

###  Latitude vs. Temperature

In [ ]:


plt.scatter(x_axis_lat, 
            y_axis_temp, 
            s=10*urban_driver_count, c="coral", 
            edgecolor="black", linewidths=1, marker="o", 
            alpha=0.8, label="Urban")

x_axis =np.arange(0,)
plt.title("Latitude vd. Temperature)")
plt.ylabel("Temperature (F)")
plt.xlabel("Latitude")
plt.xlim((-90,90))
plt.grid(True)

# Save Figure
plt.savefig("temperature.png")

# Show plot
plt.show()

### Latitude vs. Humidity

In [ ]:
plt.scatter(x_axis_lat, 
            y_axis_humidity, 
            s=10*urban_driver_count, c="coral", 
            edgecolor="black", linewidths=1, marker="o", 
            alpha=0.8, label="Urban")

x_axis =np.arange(0,)
plt.title("Latitude vd. Temperature)")
plt.ylabel("Temperature (F)")
plt.xlabel("Latitude")
plt.xlim((-90,90))
plt.grid(True)

# Save Figure
plt.savefig("humidity.png")

# Show plot
plt.show()

### Latitude vs. Cloudiness

In [ ]:
plt.scatter(x_axis_lat, 
            y_axis_humidity, 
            s=10*urban_driver_count, c="coral", 
            edgecolor="black", linewidths=1, marker="o", 
            alpha=0.8, label="Urban")

x_axis =np.arange(0,)
plt.title("Latitude vd. Temperature)")
plt.ylabel("Temperature (F)")
plt.xlabel("Latitude")
plt.xlim((-90,90))
plt.grid(True)

# Save Figure
plt.savefig("cloudiness.png")

# Show plot
plt.show()

### Latitude vs. Wind Speed

In [ ]:
plt.scatter(x_axis_lat, 
            y_axis_humidity, 
            s=10*urban_driver_count, c="coral", 
            edgecolor="black", linewidths=1, marker="o", 
            alpha=0.8, label="Urban")

x_axis =np.arange(0,)
plt.title("Latitude vd. Temperature)")
plt.ylabel("Temperature (F)")
plt.xlabel("Latitude")
plt.xlim((-90,90))
plt.grid(True)

# Save Figure
plt.savefig("wind speed.png")

# Show plot
plt.show()